### ISSUE TITLE
Issue with courses.

### ISSUE THREAD

**Issue by thom8047** [June907/CS350-Team#1]
I'm not sure if this is the right repo, but I saw the docs file getting updated a couple hours ago, so I hope this ones right. I noticed that, after making an account and trying to get into courses, only two people had courses that populated the assignments, grades, and discussions tab. I'm sure this is an issue because when I tried to create my own course, and I tried to make an assignment, grade, or discussion it brought me to an error page. I also saw that the everyone after the TestUser who made a course, didn't have assignments, grades, or discussions and I couldn't actually join the course. Great work on the page, I liked the courses I could join.

Suggestion: Maybe having the grades populate as [--/100] instead of [0/100] when an assignments submitted, that way only the instructor can set the grade and change it.

**Comment by June907** [comment]
Hi, Thom, I just tested our page, and I can successfully create courses, assignment and post discussion, I'm not sure why does it give you an error, but everything you said above it works fine to me so far still. And we will make small modifications to the grading, thank you for giving us feedback.

**Comment by June907** [comment]
> I'm not sure if this is the right repo, but I saw the docs file getting updated a couple hours ago, so I hope this ones right. I noticed that, after making an account and trying to get into courses, only two people had courses that populated the assignments, grades, and discussions tab. I'm sure this is an issue because when I tried to create my own course, and I tried to make an assignment, grade, or discussion it brought me to an error page. I also saw that the everyone after the TestUser who made a course, didn't have assignments, grades, or discussions and I couldn't actually join the course. Great work on the page, I liked the courses I could join.
> 
> Suggestion: Maybe having the grades populate as [--/100] instead of [0/100] when an assignment submitted, that way only the instructor can set the grade and change it.

Hi, Thom, the cs200 and cs350 classes were really early test for classes, therefore, it does not get assigned to groups, that's why you can't join them, but all the other classes you created or other user-created you will be able to join them. Also, I am not sure why is creating a discussion post will give you an error, but our team tested it twice, from creating new accounts to create assignments, courses, post, we didn't run into any error, if you could walk me through how you get an error specificly step by step that'll be great. Thank you for your feedback.

**Comment by thom8047** [comment]
> > I'm not sure if this is the right repo, but I saw the docs file getting updated a couple hours ago, so I hope this ones right. I noticed that, after making an account and trying to get into courses, only two people had courses that populated the assignments, grades, and discussions tab. I'm sure this is an issue because when I tried to create my own course, and I tried to make an assignment, grade, or discussion it brought me to an error page. I also saw that the everyone after the TestUser who made a course, didn't have assignments, grades, or discussions and I couldn't actually join the course. Great work on the page, I liked the courses I could join.
> > Suggestion: Maybe having the grades populate as [--/100] instead of [0/100] when an assignment submitted, that way only the instructor can set the grade and change it.
> 
> Hi, Thom, the cs200 and cs350 classes were really early test for classes, therefore, it does not get assigned to groups, that's why you can't join them, but all the other classes you created or other user-created you will be able to join them. Also, I am not sure why is creating a discussion post will give you an error, but our team tested it twice, from creating new accounts to create assignments, courses, post, we didn't run into any error, if you could walk me through how you get an error specificly step by step that'll be great. Thank you for your feedback.

Hey, yes I'm assuming you guys are presenting today, so I created a course, then it sent me to the course page and, the page I was redirected to when I created the course, there were the three links on the right side of the page, the Assignments, Grades, and Discussion links and when I clicked each one it threw an error in Django. It sent me to an error page but I didn't read through or anything. So to clarify, it was right as I made the new course, and that redirect page is where I got the error, when I tried to create an assignment. Hope this helps!

**Comment by ewhalenkamp** [comment]
This issue has been fixed, and will be deployed in tonight's push to PythonAnywhere. Thanks for the log!
