### ISSUE TITLE
File type suggestion

### ISSUE THREAD

**Issue by Adam1400** [June907/CS350-Team#2]
Instead of submitting assignments as text, consider having the user upload a file instead.  I believe django can accept file uploads... might be an easy migration in your database. However, if it would conflict with other feature, don't worry about it. 
Over all good job!

**Comment by ewhalenkamp** [comment]
File uploads were initially the plan for submissions, but troubles with file storage getting set up and worries for individual users' safety necessitated the swap to plain text. We can look to include this in a future build. Thanks for the log!
