### ISSUE TITLE
Spacing removed in assignment description

### ISSUE THREAD

**Issue by KevinBRitter** [June907/CS350-Team#3]
I'm setting up a beginner assignment for my course and in the description section I added a few video links with descriptions but the new line space between each was removed on save and now they are difficult to read separately.  Adding markdown '-' character didn't turn the spaces into a list.

**Comment by ewhalenkamp** [comment]
This issue has been fixed, and will be deployed in tonight's push to PythonAnywhere. Thanks for the log!
