### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by SProv7615** [June907/CS350-Team#5]
While the overall project looks good, just a few nitpicks.
When I made an account, it brought me back to the homepage and said, "New account made for (the account name)", but it hadn't signed me in, making me a bit surprised when it gave me a server error. You might want to have it either sign in automatically, or bring us to the sign-in page.
Secondly, when making a post, two minor nitpicks. If you click enter and try to start a new line for that post, it ignores it after you submit it. Secondly, it has two bullets when you review the post: the message itself, and the time. The second bulletpoint seems a bit unnecessary, making it look like there's two comments or something!
Anyways, that's all. Overall, quite nice looking.

**Comment by ewhalenkamp** [comment]
The registration bug is odd, and we'll be looking into that as time passes.
The newline functionality has been added and will be deployed with tonight's update to PythonAnywhere. As for the discussion, it's been our intention to change the CSS around there for a while, and it may be included in a future build. Thanks for the log!
