### ISSUE TITLE
Incorrect Times on Discussion Posting

### ISSUE THREAD

**Issue by thom1664** [June907/CS350-Team#8]
You guys did a spectacular job with this project! Honestly feels like a simple version of our current canvas I'd say this is one of the best projects in the class!! Overall I only found the issue of the time postings under discussions to be about 7 hours ahead of what the actual time was. Otherwise great work!

**Comment by ewhalenkamp** [comment]
This issue has been resolved, and should be patched in the upcoming version of the site. Thanks for the feedback!
